version: '3.9'
services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    build: .
    environment:
      MONGO_URI: mongodb://mongo:27017
      API_KEY: ${API_KEY:-changeme}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:8000/ready" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - "8081:8081"
volumes:
  mongo_data: {}
