#!/bin/bash

echo "🌍 NETWORK ACCESS CONFIGURATION"
echo "==============================="
echo ""
echo "✅ Your IP added: 77.137.66.58"
echo ""
echo "🚀 NEXT: Allow Heroku to connect"
echo ""
echo "📋 STEPS IN MONGODB ATLAS:"
echo ""
echo "1. 🌐 Go to 'Network Access' in left sidebar"
echo "2. ➕ Click 'Add IP Address' button"
echo "3. 🌍 Choose 'Allow access from anywhere'"
echo "   └─ This adds: 0.0.0.0/0"
echo "4. ✅ Click 'Confirm'"
echo ""
echo "💡 Why this is needed:"
echo "   - Your IP (77.137.66.58) = for local development"
echo "   - 0.0.0.0/0 = for Heroku deployment"
echo ""
echo "🔒 Security note: This is standard for cloud deployments"
echo ""
echo "📞 After adding 0.0.0.0/0, get your connection string from:"
echo "   Clusters → Connect → Connect your application"
