#!/bin/bash

echo "🎯 FINALIZING YOUR MONGODB ATLAS SETUP"
echo "======================================"
echo ""
echo "✅ Database User Created:"
echo "   Username: a_db_user"
echo "   Password: ZhNMqELhwIphBte9"
echo ""
echo "📋 REMAINING STEPS:"
echo ""
echo "1. 🌍 NETWORK ACCESS (if not done):"
echo "   ├─ Go to 'Network Access' in left sidebar"
echo "   ├─ Click 'Add IP Address'"
echo "   └─ Choose 'Allow access from anywhere (0.0.0.0/0)'"
echo ""
echo "2. 🔗 GET CONNECTION STRING:"
echo "   ├─ Go to 'Clusters' in left sidebar"
echo "   ├─ Click 'Connect' button on your cluster"
echo "   ├─ Choose 'Connect your application'"
echo "   ├─ Driver: Python, Version: 3.6+"
echo "   └─ Copy the connection string"
echo ""
echo "3. 🔧 MODIFY CONNECTION STRING:"
echo "   Replace <password> with: ZhNMqELhwIphBte9"
echo "   Replace <dbname> with: talent_match"
echo ""
echo "💡 Your final connection string should look like:"
echo "mongodb+srv://a_db_user:ZhNMqELhwIphBte9@cluster0.xxxxx.mongodb.net/talent_match?retryWrites=true&w=majority"
echo ""
echo "🚀 DEPLOY TO HEROKU (copy your actual connection string):"
echo "heroku config:set MONGO_URI='mongodb+srv://a_db_user:ZhNMqELhwIphBte9@[your-cluster-url]/talent_match?retryWrites=true&w=majority' -a scoreagents"
echo ""
echo "📞 When you have the connection string, paste it here and I'll deploy it!"
