#!/bin/bash

echo "🆓 FREE MongoDB Atlas Setup - Zero Cost Solution"
echo "================================================"
echo ""
echo "This is COMPLETELY FREE forever with these limits:"
echo "✅ 512MB storage"
echo "✅ Shared cluster"
echo "✅ Perfect for your app size"
echo ""
echo "📋 STEP-BY-STEP (5 minutes):"
echo ""
echo "1. 🌐 Open: https://cloud.mongodb.com/"
echo "2. 📝 Sign up with email (free account)"
echo "3. 🎯 Create new project: 'AMIS-Production'"
echo ""
echo "4. 🆓 CREATE FREE DATABASE:"
echo "   ├─ Click 'Build a Database'"
echo "   ├─ Choose 'M0 Sandbox' (FREE FOREVER)"
echo "   ├─ Provider: AWS"
echo "   ├─ Region: Choose closest to you"
echo "   └─ Name: 'amis-cluster'"
echo ""
echo "5. 🔐 DATABASE USER:"
echo "   ├─ Username: amis_user"
echo "   ├─ Password: [generate strong - SAVE IT!]"
echo "   └─ Role: Atlas Admin"
echo ""
echo "6. 🌍 NETWORK ACCESS:"
echo "   ├─ Add IP Address"
echo "   └─ Choose: 'Allow access from anywhere (0.0.0.0/0)'"
echo ""
echo "7. 🔗 CONNECTION STRING:"
echo "   ├─ Go to Clusters → Connect"
echo "   ├─ Choose 'Connect your application'"
echo "   ├─ Driver: Python, Version: 3.6+"
echo "   └─ Copy the full connection string"
echo ""
echo "💡 Your connection string will look like:"
echo "mongodb+srv://amis_user:<password>@amis-cluster.xxxxx.mongodb.net/talent_match?retryWrites=true&w=majority"
echo ""
echo "🚀 DEPLOY TO HEROKU:"
echo "heroku config:set MONGO_URI='[your-connection-string]' -a scoreagents"
echo ""
echo "⚡ Total monthly cost: $0.00"
