#!/bin/bash

# MongoDB Atlas Setup Script for Heroku
# This script helps you set up MongoDB Atlas and configure it for your Heroku app

echo "🚀 MongoDB Atlas Setup for Heroku Deployment"
echo "============================================="
echo ""
echo "To get your app working on Heroku, you need a cloud MongoDB database."
echo "MongoDB Atlas provides a free tier that's perfect for this."
echo ""
echo "📋 STEP-BY-STEP GUIDE:"
echo ""
echo "1. 🌐 Go to: https://cloud.mongodb.com/"
echo "2. 📝 Sign up or log in with your email"
echo "3. 🎯 Create a NEW PROJECT (e.g., 'AMIS-Heroku')"
echo "4. 🏗️  BUILD A DATABASE:"
echo "   - Choose 'M0 Sandbox' (FREE)"
echo "   - Select AWS and closest region"
echo "   - Name: 'amis-cluster'"
echo ""
echo "5. 🔐 DATABASE ACCESS:"
echo "   - Go to 'Database Access' in left sidebar"
echo "   - Click 'Add New Database User'"
echo "   - Username: amis_user"
echo "   - Password: [generate strong password - SAVE THIS!]"
echo "   - Role: 'Atlas Admin'"
echo ""
echo "6. 🌍 NETWORK ACCESS:"
echo "   - Go to 'Network Access' in left sidebar"  
echo "   - Click 'Add IP Address'"
echo "   - Choose 'Allow access from anywhere (0.0.0.0/0)'"
echo "   - This allows Heroku to connect"
echo ""
echo "7. 🔗 GET CONNECTION STRING:"
echo "   - Go back to 'Clusters'"
echo "   - Click 'Connect' on your cluster"
echo "   - Choose 'Connect your application'"
echo "   - Copy the connection string"
echo "   - It looks like: mongodb+srv://amis_user:<password>@amis-cluster.xxxxx.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
echo ""
echo "8. 🚀 CONFIGURE HEROKU:"
echo "   After you get your connection string, run:"
echo "   heroku config:set MONGO_URI='[your connection string]' -a scoreagents"
echo ""
echo "⚡ QUICK ALTERNATIVE:"
echo "If you want to test immediately, I can help set up a temporary solution."
echo ""
echo "📞 When ready, come back and tell me your MongoDB connection string!"
